services:

  admin_backend:
    build: .
    ports:
      - 8004:8000
    volumes:
      - .:/app
    command: 'php artisan serve --host=0.0.0.0'
    depends_on:
      - admin_db
    networks:
      - admin
      - users

  admin_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    networks:
      - admin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
        PMA_ARBITRARY: 1
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    networks:
      - admin
      


networks:
  admin:
  users:
    name: users
    external: true

