services:

  ambassador_backend:
    build: .
    ports:
      - 8003:8000
    volumes:
      - .:/app
    command: 'php artisan serve --host=0.0.0.0'
    depends_on:
      - ambassador_db
    networks:
      - ambassador
      - users

  ambassador_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    networks:
      - ambassador

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
        PMA_ARBITRARY: 1
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    networks:
      - ambassador
      
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - ambassador

networks:
  ambassador:
  users:
    name: users
    external: true

