version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: 'php artisan serve --host=0.0.0.0'
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33066:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8080:8000'
    environment:
        PMA_ARBITRARY: 1
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
  redis:
    image: redis
    ports:
      - 6379:6379
