services:
  email_queue:
    build: .
    image: hassanelshazlyeida/email:0.0.1
    environment:
      MAIL_MAILER : smtp
      MAIL_HOST : sandbox.smtp.mailtrap.io
      MAIL_PORT : 2525
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION : tls
      KAFKA_TOPIC : email_topic
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_SECURITY_PROTOCOL : SASL_SSL
      KAFKA_SASL_MECHANISMS : PLAIN
      KAFKA_SASL_USERNAME: ${KAFKA_SASL_USERNAME}
      KAFKA_SASL_PASSWORD: ${KAFKA_SASL_PASSWORD}
      KAFKA_GROUP_ID : mygroup

    command: 'php artisan queue:work'