services:
  users_backend:
    build: .
    ports:
      - 8001:8000
    volumes:
      - .:/app
    command: 'php artisan serve --host=0.0.0.0'
    depends_on:
      - users_db

  users_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
  users_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8081:8001'
    environment:
        PMA_ARBITRARY: 1
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'


